### ISSUE TITLE
Error while running AMP validation using API end point

### ISSUE THREAD

**Issue by amandv** [ampproject/ampbench#117]
_http_outgoing.js:491
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (F:\ampbench\ampbench\node_modules\express\lib\resp
onse.js:767:10)
    at ServerResponse.send (F:\ampbench\ampbench\node_modules\express\lib\respon
se.js:170:12)
    at ServerResponse.json (F:\ampbench\ampbench\node_modules\express\lib\respon
se.js:267:15)
    at on_output (F:\ampbench\ampbench\ampbench_routes.js:534:29)
    at IncomingMessage.res.on (F:\ampbench\ampbench\ampbench_lib.js:961:25)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ampbench@1.0.0 start: `node ampbench_main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ampbench@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by pietergreyling** [comment]
Hi amandv,

Thank you for raising this issue.

Could you please provide the test details so that we can actually reproduce this outcome in order to investigate.

Thanks //pieter
